import xlsx from 'xlsx';
import path from 'path';

const products = [
    // --- CRÉDITO ---
    {
        sku: "TR-CRED-001",
        name: "Lending Intelligence Engine",
        description: "Plataforma de decisão de crédito em tempo real que utiliza modelos de Gradient Boosting para análise de bureau e comportamento transacional.",
        category: "Crédito / Risk & Compliance",
        price: 45000,
        stock_status: "in_stock",
        horizonte: "H1",
        bu: "Risk & Compliance",
        squad: "Credit AI",
        owner: "Ana Silva",
        mercado: "B2B",
        revenue: "450k",
        pricing: "SaaS + Fee por consulta",
        problem: "Alta taxa de inadimplência e lentidão no processo de aprovação manual.",
        use_cases: "Aprovação instantânea de cartões, Redução de churn financeiro, Score proprietário B2B",
        solutions: "Engine de regras em Python, Integração nativa com Serasa/Boa Vista, Modelos de ML auto-explicáveis (SHAP)",
        tech: "Python, XGBoost, FastAPI, PostgreSQL"
    },
    {
        sku: "TR-CRED-002",
        name: "Fraud Shield Biometrics",
        description: "Sistema de prevenção a fraude por identidade, integrando biometria facial e análise de grafos de relacionamento.",
        category: "Crédito / Fraud Prevention",
        price: 32000,
        stock_status: "in_stock",
        horizonte: "H1",
        bu: "Risk & Compliance",
        squad: "Shield Squad",
        owner: "Bruno Costa",
        mercado: "B2B",
        revenue: "280k",
        pricing: "Assinatura Mensal",
        problem: "Aumento de fraudes de identidade (account takeover) em abertura de contas digital.",
        use_cases: "Onboarding digital seguro, Validação de transações suspeitas, KYB automatizado",
        solutions: "Face Match SDK, Análise de device fingerprinting, Redes neurais para detecção de anomalias",
        tech: "TensorFlow, Node.js, AWS Rekognition, Neo4j"
    },
    {
        sku: "TR-CRED-003",
        name: "Collections Smart Orchestrator",
        description: "Orquestrador de cobrança amigável que utiliza IA para definir o melhor canal e tom de voz para cada cliente inadimplente.",
        category: "Crédito / Collections Tech",
        price: 15000,
        stock_status: "in_stock",
        horizonte: "H2",
        bu: "Collections Tech",
        squad: "Recovery",
        owner: "Carlos Santos",
        mercado: "B2B2C",
        revenue: "120k",
        pricing: "Sucess Fee sobre recuperação",
        problem: "Baixa eficiência de call centers e alto custo de recuperação de crédito.",
        use_cases: "Recuperação de carteiras em atraso, Renegociação automática via WhatsApp, Scoring de propensão ao pagamento",
        solutions: "NLP para análise de sentimento, Chatbot cognitivo, Dashboard de performance de carteira",
        tech: "Google Dialogflow, Python, React, Supabase"
    },
    {
        sku: "TR-CRED-004",
        name: "SMB Credit Score Plus",
        description: "Score de crédito focado exclusivamente em pequenas e médias empresas, analisando dados de faturamento e notas fiscais.",
        category: "Crédito / Risk & Compliance",
        price: 28000,
        stock_status: "in_stock",
        horizonte: "H2",
        bu: "Risk & Compliance",
        squad: "SME Vision",
        owner: "Daniela Lima",
        mercado: "B2B",
        revenue: "210k",
        pricing: "Licenciamento Anual",
        problem: "Falta de dados de birô tradicionais para Pequenas e Médias empresas (PMEs).",
        use_cases: "Crédito PJ fumaça de cartão, Financiamento de capital de giro, Antecipação de recebíveis",
        solutions: "Integração Open Finance, Extrator de XML de Notas Fiscais, Modelo de risco setorial",
        tech: "Python, Spark, Power BI, Azure"
    },
    {
        sku: "TR-CRED-005",
        name: "Real Estate Risk Valuator",
        description: "Análise preditiva de risco imobiliário cruzando dados geográficos, históricos de valorização e risco jurídico.",
        category: "Crédito / Real Estate",
        price: 55000,
        stock_status: "in_stock",
        horizonte: "H3",
        bu: "Risk & Compliance",
        squad: "PropTech AI",
        owner: "Eduardo Rocha",
        mercado: "B2B",
        revenue: "85k",
        pricing: "Transacional / Por Laudo",
        problem: "Subavaliação ou superavaliação técnica de garantias imobiliárias.",
        use_cases: "Garantia de Home Equity, Análise de portfólio de FIIs, Avaliação automática (AVM)",
        solutions: "GIS Data Integration, Web Scraping de portais imobiliários, Modelos Hedônicos",
        tech: "Python, QGIS, MongoDB, Docker"
    },
    {
        sku: "TR-CRED-006",
        name: "Auto Financing Bot",
        description: "Assistente virtual para simulação e pré-aprovação de financiamento de veículos em concessionárias.",
        category: "Crédito / Lending Engine",
        price: 12000,
        stock_status: "in_stock",
        horizonte: "H1",
        bu: "Lending Engine",
        squad: "Auto Squad",
        owner: "Fernanda Oliveira",
        mercado: "B2B2C",
        revenue: "310k",
        pricing: "SaaS + Fee por Lead",
        problem: "Fricção no ponto de venda e desistência do cliente por demora na análise.",
        use_cases: "Auto-atendimento em showrooms, Qualificação de leads quente, Integração com bancos de montadora",
        solutions: "Interface Mobile First, OCR de documento do veículo, API de consulta de tabela FIPE",
        tech: "React Native, Node.js, Redis, Google Cloud"
    },
    {
        sku: "TR-CRED-007",
        name: "Open Finance Aggregator",
        description: "Hub de conexão com APIs do Open Finance para consolidação de extratos e categorização automática de gastos.",
        category: "Crédito / Data Infrastructure",
        price: 38000,
        stock_status: "in_stock",
        horizonte: "H2",
        bu: "Lending Engine",
        squad: "Connect",
        owner: "Gustavo Lima",
        mercado: "B2B",
        revenue: "155k",
        pricing: "API Call Based",
        problem: "Fragmentação de dados bancários e dificuldade em ver o 'share of wallet' do cliente.",
        use_cases: "PFM (Personal Finance Manager), Decisão de limite de crédito dinâmico, Ofertas personalizadas",
        solutions: "Conector certificado BACEN, Engine de categorização via LLM, Dashboard de conciliação",
        tech: "Go, Kubernetes, Gemini 1.5 Flash, PostgreSQL"
    },
    {
        sku: "TR-CRED-008",
        name: "Legal Risk Scrapper",
        description: "Ferramenta de busca automatizada em tribunais para identificação de processos que impactam o risco de crédito.",
        category: "Crédito / Risk & Compliance",
        price: 22000,
        stock_status: "in_stock",
        horizonte: "H1",
        bu: "Risk & Compliance",
        squad: "LawTech",
        owner: "Helena Souza",
        mercado: "B2B",
        revenue: "190k",
        pricing: "Fee mensal por CPF/CNPJ monitorado",
        problem: "Custos altíssimos com advogados para pesquisas manuais de 'nada consta'.",
        use_cases: "Due diligence de grandes contas, Monitoramento de carteira ativa, Compliance preventivo",
        solutions: "Crawler distribuído, Parser de PDFs jurídicos, Scoring de gravidade processual",
        tech: "Python, Selenium, ElasticSearch, RabbitMQ"
    },
    {
        sku: "TR-CRED-009",
        name: "Agro Credit Vision",
        description: "Análise de risco para crédito agrícola utilizando imagens de satélite e dados meteorológicos para prever produtividade.",
        category: "Crédito / Agribusiness",
        price: 65000,
        stock_status: "in_stock",
        horizonte: "H3",
        bu: "Risk & Compliance",
        squad: "AgroData",
        owner: "Igor Martins",
        mercado: "B2B",
        revenue: "40k",
        pricing: "Project Based + Fee por Safra",
        problem: "Incerteza climática e falta de garantias reais para empréstimos rurais.",
        use_cases: "Seguro safra paramétrico, Financiamento de insumos, Monitoramento de área plantada",
        solutions: "Computer Vision para NDVI, Integração com sensores IoT, Modelagem de séries temporais",
        tech: "Python, PyTorch, Sentinel Hub, BigQuery"
    },
    {
        sku: "TR-CRED-010",
        name: "Identity Graph Master",
        description: "Plataforma de visualização de vínculos entre CPFs e CNPJs para detecção de grupos econômicos e colusão.",
        category: "Crédito / Risk & Compliance",
        price: 49000,
        stock_status: "in_stock",
        horizonte: "H2",
        bu: "Risk & Compliance",
        squad: "Graph Squad",
        owner: "Juliana Alves",
        mercado: "B2B",
        revenue: "130k",
        pricing: "Licença por Usuário",
        problem: "Fraude estruturada onde diversos CNPJs de fachada ocultam o beneficiário final.",
        use_cases: "Prevenção a lavagem de dinheiro (AML), Recuperação judicial, Crédito corporativo complexo",
        solutions: "Banco de dados em grafo, Algoritmos de comunidade, Link Prediction",
        tech: "Neo4j, Cypher, Java, React Flow"
    },
    {
        sku: "TR-CRED-011",
        name: "Payroll Loan Engine",
        description: "Motor de consignado público e privado com integração direta via RH e órgãos governamentais.",
        category: "Crédito / Lending Engine",
        price: 25000,
        stock_status: "in_stock",
        horizonte: "H1",
        bu: "Lending Engine",
        squad: "Payroll AI",
        owner: "Ana Silva",
        mercado: "B2B2C",
        revenue: "380k",
        pricing: "Por contrato gerado",
        problem: "Processo de averbação lento e erro humano em cálculos de margem consignável.",
        use_cases: "Benefício corporativo, Crédito para servidor público, Antecipação do 13º salário",
        solutions: "Certificação digital integrada, Engine de cálculo de margem, Porta de entrada mobile",
        tech: "Java, Spring Boot, SQL Server, Redis"
    },
    {
        sku: "TR-CRED-012",
        name: "Credit Policy Simulator",
        description: "Sandbox para gerentes de risco simularem mudanças em políticas de crédito antes de irem para produção.",
        category: "Crédito / Risk & Compliance",
        price: 33000,
        stock_status: "in_stock",
        horizonte: "H2",
        bu: "Risk & Compliance",
        squad: "Strategy",
        owner: "Bruno Costa",
        mercado: "B2B",
        revenue: "115k",
        pricing: "Fee Mensal de Plataforma",
        problem: "Medo de implementar novas regras de crédito e causar aumentos bruscos na inadimplência.",
        use_cases: "Teste A/B de políticas, Estratégia de expansão de limites, Backtest de modelos",
        solutions: "Simulação de Monte Carlo, Visualização de curva ROC, Exportação de regras PMML",
        tech: "R, Python, Shiny, AWS Sagemaker"
    },

    // --- SEGUROS ---
    {
        sku: "TR-INS-001",
        name: "Telematics Driver Scoring",
        description: "Algoritmo que analisa dados de GPS e acelerômetro de smartphones para calcular perfil de risco de motoristas.",
        category: "Seguros / Mobility",
        price: 21000,
        stock_status: "in_stock",
        horizonte: "H2",
        bu: "Underwriting AI",
        squad: "Ubi Squad",
        owner: "Carlos Santos",
        mercado: "B2B2C",
        revenue: "220k",
        pricing: "Por usuário ativo/mes",
        problem: "Preço do seguro auto baseado apenas em dados demográficos (CEP, Idade).",
        use_cases: "Pay As You Drive (PAYD), Bonus por bom comportamento, Gestão de frotas",
        solutions: "Sensor Fusion em Mobile, Map matching, Detecção de freadas bruscas e curvas",
        tech: "Swift, Kotlin, Python, Google Maps API"
    },
    {
        sku: "TR-INS-002",
        name: "Claims Vision Auditor",
        description: "IA que analisa fotos de batidas de veículos para estimar o valor do conserto e detectar fraudes em sinistros.",
        category: "Seguros / Claims Analytics",
        price: 42000,
        stock_status: "in_stock",
        horizonte: "H1",
        bu: "Claims Analytics",
        squad: "Visual Audit",
        owner: "Daniela Lima",
        mercado: "B2B",
        revenue: "410k",
        pricing: "Por sinistro auditado",
        problem: "Vistorias demoradas e conluio entre oficinas e segurados para inflar orçamentos.",
        use_cases: "Vistoria prévia digital, Regulação de sinistro automática, Detecção de peça trocada",
        solutions: "Deep Learning para segmentação de dano, Catálogo de preços de peças integrado, API de fotos",
        tech: "Python, PyTorch, OpenCV, SQLite"
    },
    {
        sku: "TR-INS-003",
        name: "Life Insurance Smart Pricing",
        description: "Modelo estatístico que cruza dados de estilo de vida e histórico de saúde para precificar seguro de vida individual.",
        category: "Seguros / Actuarial",
        price: 37000,
        stock_status: "in_stock",
        horizonte: "H2",
        bu: "Actuarial Research",
        squad: "Life AI",
        owner: "Eduardo Rocha",
        mercado: "B2C",
        revenue: "140k",
        pricing: "Fee de Setup + Transacional",
        problem: "Questionários de saúde longos e baixa conversão por processos invasivos.",
        use_cases: "Venda direta digital, Underwriting simplificado, Descontos por passos diários",
        solutions: "Integração Gadgets (Apple Health/Google Fit), Scoring de longevidade, Modelo GLM",
        tech: "R, Python, AWS Lambda, DynamoDB"
    },
    {
        sku: "TR-INS-004",
        name: "Home IoT Protector",
        description: "Seguro residencial conectado com sensores de fumaça e vazamento de água integrados para prevenir sinistros.",
        category: "Seguros / IoT",
        price: 18000,
        stock_status: "in_stock",
        horizonte: "H3",
        bu: "Underwriting AI",
        squad: "Smart Home",
        owner: "Fernanda Oliveira",
        mercado: "B2C",
        revenue: "55k",
        pricing: "Mensal por dispositivo",
        problem: "Seguro residencial passivo que só atua após a perda total da residência.",
        use_cases: "Prevenção de danos por água, Redução de prêmio por segurança ativa, Assistência técnica preditiva",
        solutions: "Integração MQTT para sensores, Alertas push em tempo real, Acionamento automático de reparo",
        tech: "Node.js, C++ (Firmware), MQTT, InfluxDB"
    },
    {
        sku: "TR-INS-005",
        name: "Cyber Risk Analytics",
        description: "Análise de vulnerabilidades de infraestrutura TI de empresas para cálculo de prêmio de seguro cibernético.",
        category: "Seguros / Corporate",
        price: 52000,
        stock_status: "in_stock",
        horizonte: "H2",
        bu: "Actuarial Research",
        squad: "Cyber Defense",
        owner: "Gustavo Lima",
        mercado: "B2B",
        revenue: "195k",
        pricing: "Annual Retainer",
        problem: "Dificuldade em quantificar o risco financeiro de um ataque de Ransomware.",
        use_cases: "Precificação de apólices Cyber, Auditoria de segurança externa, Dashboard de risco CISO",
        solutions: "Port scanner passivo, Análise de vazamentos na Dark Web, Quantificação VaR (Value at Risk)",
        tech: "Python, Nmap, Go, Tableau"
    },
    {
        sku: "TR-INS-006",
        name: "Health Insurance Optimizer",
        description: "Algoritmo de recomendação de rede de hospitais e médicos para redução de custo de sinistralidade em planos empresariais.",
        category: "Seguros / Health Analytics",
        price: 33000,
        stock_status: "in_stock",
        horizonte: "H1",
        bu: "Claims Analytics",
        squad: "Health Cost",
        owner: "Helena Souza",
        mercado: "B2B",
        revenue: "430k",
        pricing: "Percentual sobre redução de custo",
        problem: "Incentivos errados e excesso de exames desnecessários que inflam o custo do benefício.",
        use_cases: "Gestão de crônicos, Direcionamento para médicos resolutivos, Detecção de fraude em reembolsos",
        solutions: "Clustering de perfis de pacientes, Score de resolutividade médica, Engine de auditoria de NFs",
        tech: "Spark, Python, Scala, BigQuery"
    },
    {
        sku: "TR-INS-007",
        name: "Flight Delay Payback",
        description: "Seguro viagem paramétrico que paga o cliente automaticamente quando o atraso de um voo é detectado por base pública.",
        category: "Seguros / Travel",
        price: 9000,
        stock_status: "in_stock",
        horizonte: "H3",
        bu: "Underwriting AI",
        squad: "TravelTech",
        owner: "Igor Martins",
        mercado: "B2C",
        revenue: "75k",
        pricing: "Por bilhete emitido",
        problem: "Burocracia excessiva para receber indenização por atrasos simples.",
        use_cases: "Voucher de sala VIP automático, Checkout simplificado em e-commerce, Reembolso instantâneo",
        solutions: "Integração FlightStats API, Smart Contracts para liquidação, Bot de notificação",
        tech: "Node.js, Ethereum (Solidity), API Gateway, Firebase"
    },
    {
        sku: "TR-INS-008",
        name: "Agro Crop Guardian",
        description: "Plataforma de seguro agrícola baseada em índices climáticos históricos e monitoramento via satélite em tempo real.",
        category: "Seguros / Agribusiness",
        price: 68000,
        stock_status: "in_stock",
        horizonte: "H1",
        bu: "Actuarial Research",
        squad: "Agro Shield",
        owner: "Juliana Alves",
        mercado: "B2B",
        revenue: "510k",
        pricing: "Fee por Hectare",
        problem: "Perdas catastróficas por seca ou geada sem cobertura adequada e rápida.",
        use_cases: "Proteção de safra de soja/milho, Garantia de financiamento rural, Crédito de carbono integrado",
        solutions: "Dados de satélite Sentinel (ESA), Modelagem de risco climático regional, App de campo para peritos",
        tech: "Python, GIS, Docker, GeoServer"
    },
    {
        sku: "TR-INS-009",
        name: "Renewable Energy Insurer",
        description: "Precificação dinâmica para parques eólicos e solares baseada em previsão de geração e risco de interrupção operacional.",
        category: "Seguros / Green Energy",
        price: 75000,
        stock_status: "in_stock",
        horizonte: "H3",
        bu: "Actuarial Research",
        squad: "Energy AI",
        owner: "Ana Silva",
        mercado: "B2B",
        revenue: "30k",
        pricing: "Custom/Project Based",
        problem: "Falta de histórico de sinistros para ativos de energia renovável de larga escala.",
        use_cases: "Seguro de performance de geração, Proteção de infraestrutura solar, Cobertura climática para eólicas",
        solutions: "Time series forecasting para geração, Digital Twins dos ativos, Simulação de ventos históricos",
        tech: "Python, TensorFlow, InfluxDB, Unity (Visual)"
    },
    {
        sku: "TR-INS-010",
        name: "Pet Health AI Plan",
        description: "Plataforma de plano de saúde para pets com telemedicina e análise de risco por raça e idade do animal.",
        category: "Seguros / Pet",
        price: 14000,
        stock_status: "in_stock",
        horizonte: "H1",
        bu: "Underwriting AI",
        squad: "Pet Squad",
        owner: "Bruno Costa",
        mercado: "B2C",
        revenue: "295k",
        pricing: "Assinatura Mensal",
        problem: "Custos veterinários imprevisíveis e falta de dados sobre saúde animal no Brasil.",
        use_cases: "Tele-vet 24h, Microchipagem com carteira de vacinação digital, Descontos em parceiros",
        solutions: "App para agendamento, Sistema de triagem via chatbot, Prontuário eletrônico unificado",
        tech: "Flutter, Node.js, PostgreSQL, Twilio"
    },
    {
        sku: "TR-INS-011",
        name: "Cargo Track Insight",
        description: "Seguro de carga inteligente que mitiga risco de roubo através de rotas dinâmicas e análise de hotspots de crime.",
        category: "Seguros / Logistics",
        price: 34000,
        stock_status: "in_stock",
        horizonte: "H2",
        bu: "Claims Analytics",
        squad: "Cargo Safe",
        owner: "Carlos Santos",
        mercado: "B2B",
        revenue: "185k",
        pricing: "Fee sobre valor da carga",
        problem: "Altíssima sinistralidade em transporte de carga visada (eletro/farmacêutico).",
        use_cases: "Roteirização segura, Monitoramento de comboio, Alertas automáticos para gerenciadoras",
        solutions: "Engine de risco por trecho rodoviário, Integração com sistemas de rastreamento, IA preditiva de roubo",
        tech: "Python, Kafka, Redis, Google Maps SDK"
    },

    // --- SAÚDE ---
    {
        sku: "TR-HEALTH-001",
        name: "Clinical Flow Optimizer",
        description: "Sistema de gestão de jornada do paciente em hospitais que prevê picos de demanda no pronto-socorro.",
        category: "Saúde / Ops Optimization",
        price: 48000,
        stock_status: "in_stock",
        horizonte: "H1",
        bu: "Ops Optimization",
        squad: "Hospital Flow",
        owner: "Daniela Lima",
        mercado: "B2B",
        revenue: "520k",
        pricing: "Licença por Leito/Mês",
        problem: "Superlotação em horários críticos e ociosidade em outros períodos.",
        use_cases: "Dimensionamento de equipe médica, Alocação de leitos cirúrgicos, Gestão de filas de espera",
        solutions: "Modelagem de filas (Teoria das Filas), Previsão de demanda via LSTM, Dashboard de tempo real",
        tech: "Python, TensorFlow, React, SQL Server"
    },
    {
        sku: "TR-HEALTH-002",
        name: "Patient Risk Scorer",
        description: "IA que monitora sinais vitais em UTI e emite alertas precoces de sepse e parada cardiorrespiratória.",
        category: "Saúde / Clinical Data",
        price: 85000,
        stock_status: "in_stock",
        horizonte: "H2",
        bu: "Clinical Data",
        squad: "Life Alert",
        owner: "Eduardo Rocha",
        mercado: "B2B",
        revenue: "230k",
        pricing: "SaaS Per Patient",
        problem: "Identificação tardia de deterioração clínica que leva a óbitos evitáveis.",
        use_cases: "Monitoramento de UTI, Alerta de Sepse precoce, Redução de tempo de internação",
        solutions: "Integração nativa com monitores (HL7/FHIR), Algoritmos de Deep Learning, Alerta via Smartwatch",
        tech: "Python, Go, InfluxDB, Kafka"
    },
    {
        sku: "TR-HEALTH-003",
        name: "Engage Health App",
        description: "Plataforma de engajamento do paciente que automatiza lembretes de medicação e monitora doenças crônicas.",
        category: "Saúde / Patient Engagement",
        price: 19000,
        stock_status: "in_stock",
        horizonte: "H1",
        bu: "Patient Engagement",
        squad: "Patient Hub",
        owner: "Fernanda Oliveira",
        mercado: "B2B2C",
        revenue: "440k",
        pricing: "Per User Monthly",
        problem: "Baixa adesão ao tratamento médico após a alta hospitalar.",
        use_cases: "Gestão de diabetes/hipertensão, Programas de bem-estar corporativo, Pós-operatório guiado",
        solutions: "Gamificação de hábitos saudáveis, Chatbot para dúvidas de sintomas, Integração com IoT Wearables",
        tech: "React Native, Node.js, Firebase, Google Fit API"
    },
    {
        sku: "TR-HEALTH-004",
        name: "MedClaims Auditor AI",
        description: "Auditoria automática de faturas hospitalares para operadoras de saúde detectando cobranças indevidas e fraudes.",
        category: "Saúde / Financial",
        price: 55000,
        stock_status: "in_stock",
        horizonte: "H1",
        bu: "Ops Optimization",
        squad: "Audit Tech",
        owner: "Gustavo Lima",
        mercado: "B2B",
        revenue: "610k",
        pricing: "Percentual sobre glosa revertida",
        problem: "Desperdício de 20% do faturamento em erros de faturamento e fraudes técnicas.",
        use_cases: "Auditoria pré-pagamento, Detecção de 'item não utilizado', Benchmarking de custos hospitalares",
        solutions: "Engine de regras baseada em TUSS/TISS, NLP para ler evolução médica em texto livre, IA para anomalias",
        tech: "Python, BERT, MongoDB, PowerBI"
    },
    {
        sku: "TR-HEALTH-005",
        name: "Diagnostic Assistant AI",
        description: "Suporte à decisão clínica que sugere diagnósticos baseados em sintomas, exames e literatura médica atualizada.",
        category: "Saúde / Clinical Data",
        price: 92000,
        stock_status: "in_stock",
        horizonte: "H3",
        bu: "Clinical Data",
        squad: "Decision Support",
        owner: "Helena Souza",
        mercado: "B2B",
        revenue: "15k",
        pricing: "Licença Institucional",
        problem: "Erros de diagnóstico e dificuldade do médico em se manter atualizado com milhares de papers mensais.",
        use_cases: "Segunda opinião médica em oncologia, Triagem em telessaúde, Redução de protocolos desnecessários",
        solutions: "LLM treinado em literatura médica (RAG), Integração com prontuário eletrônico (PEP), Grafo de doenças",
        tech: "Python, LangChain, Gemini 1.5 Pro, Vector DB"
    },
    {
        sku: "TR-HEALTH-006",
        name: "Pharma Demand Predictor",
        description: "Otimização de estoque para farmácias e distribuidoras prevendo surtos epidemiológicos e sazonalidade regional.",
        category: "Saúde / Supply Chain",
        price: 31000,
        stock_status: "in_stock",
        horizonte: "H2",
        bu: "Ops Optimization",
        squad: "Pharma Chain",
        owner: "Igor Martins",
        mercado: "B2B",
        revenue: "180k",
        pricing: "SaaS Fees",
        problem: "Ruptura de estoque de medicamentos críticos ou excesso de itens próximos ao vencimento.",
        use_cases: "Planejamento de compras, Previsão de surto de gripe/dengue por região, Logística de vacinas",
        solutions: "Modelos de Prophet para sazonalidade, Integração com dados do Google Trends/Twitter, Cadastro Web Service",
        tech: "Python, Prophet, BigQuery, Airflow"
    },
    {
        sku: "TR-HEALTH-007",
        name: "Genome Data Analyzer",
        description: "Processamento de dados de sequenciamento genético para medicina personalizada e prevenção de riscos hereditários.",
        category: "Saúde / Clinical Data",
        price: 120000,
        stock_status: "in_stock",
        horizonte: "H3",
        bu: "Clinical Data",
        squad: "Genomics",
        owner: "Juliana Alves",
        mercado: "B2B",
        revenue: "25k",
        pricing: "Per Sequence Processed",
        problem: "Alto custo computacional e complexidade de interpretar dados genéticos brutos.",
        use_cases: "Oncologia de precisão, Testes pré-natais não invasivos, Farmacogenética",
        solutions: "Pipeline de bioinformática, Comparação com bancos globais (ClinVar/GenBank), Report automatizado",
        tech: "Nextflow, Python, HPC (AWS Batch), Rust"
    },
    {
        sku: "TR-HEALTH-008",
        name: "Remote Patient Monitoring",
        description: "Hardware + Software para monitoramento de idosos e pacientes críticos em casa com detecção de queda.",
        category: "Saúde / Mobility",
        price: 14000,
        stock_status: "in_stock",
        horizonte: "H1",
        bu: "Patient Engagement",
        squad: "Care Home",
        owner: "Ana Silva",
        mercado: "B2C",
        revenue: "320k",
        pricing: "Venda Kit + Mensalidade",
        problem: "Acidentes domésticos com idosos que vivem sozinhos e demora no socorro.",
        use_cases: "Hospital em casa (Home Care), Segurança de idosos, Gestão de reabilitação cardíaca",
        solutions: "Sensor de queda vestível, Botão de pânico IoT, Dashboard para familiares e médicos",
        tech: "Embedded C, Node.js, MQTT, Swift"
    },
    {
        sku: "TR-HEALTH-009",
        name: "Radiology Vision Hub",
        description: "IA para triagem de exames de imagem (Raio-X, Tomografia) detectando achados críticos e priorizando laudos.",
        category: "Saúde / Clinical Data",
        price: 72000,
        stock_status: "in_stock",
        horizonte: "H2",
        bu: "Clinical Data",
        squad: "RadVision",
        owner: "Bruno Costa",
        mercado: "B2B",
        revenue: "215k",
        pricing: "Per Study Processed",
        problem: "Fila de laudos longa e risco de exames urgentes 'perderem' no volume total.",
        use_cases: "Triagem de AVC em emergência, Detecção de nódulos mamários (Mamografia), Auxílio ao radiologista",
        solutions: "CNNs (Convolutional Neural Networks), Visualizador DICOM integrado, Relatório preliminar automático",
        tech: "Python, TensorFlow, Orthanc, React"
    },
    {
        sku: "TR-HEALTH-010",
        name: "Mental Health AI Screen",
        description: "Plataforma de triagem de saúde mental via análise de voz e texto para empresas oferecerem suporte preventivo.",
        category: "Saúde / Mental Health",
        price: 16000,
        stock_status: "in_stock",
        horizonte: "H3",
        bu: "Patient Engagement",
        squad: "Mind AI",
        owner: "Carlos Santos",
        mercado: "B2B",
        revenue: "65k",
        pricing: "Per Employee Monthly",
        problem: "Aumento de Burnout e depressão no trabalho sem ferramentas de detecção precoce.",
        use_cases: "Bem-estar corporativo, Alerta para RH sobre clima organizacional, Triagem para psicologia",
        solutions: "Análise de biomarcadores vocais, Sentiment Analysis de canais internos (Slack/Teams), Anonimização de dados",
        tech: "Python, Wav2Vec, HuggingFace, Supabase"
    },
    {
        sku: "TR-HEALTH-011",
        name: "Blood Bank Orchestrator",
        description: "Otimização de estoque de bolsas de sangue cruzando demanda hospitalar futura com campanhas de doação.",
        category: "Saúde / Ops Optimization",
        price: 24000,
        stock_status: "in_stock",
        horizonte: "H2",
        bu: "Ops Optimization",
        squad: "Blood Tech",
        owner: "Daniela Lima",
        mercado: "B2B",
        revenue: "95k",
        pricing: "Licença Anual",
        problem: "Vencimento de bolsas por excesso em tipos comuns e falta crítica em tipos raros.",
        use_cases: "Gestão de hemocentros, Logística de distribuição urbana, CRM de doadores recorrentes",
        solutions: "Modelo preditivo de uso por tipo sanguíneo, Automação de convocação de doadores, Rastreabilidade térmica",
        tech: "Node.js, Python, MariaDB, Docker"
    },
    {
        sku: "TR-HEALTH-012",
        name: "Telehealth Platform 360",
        description: "Plataforma completa para atendimento remoto com integração de prontuário e prescrição digital certificada.",
        category: "Saúde / Mobility",
        price: 18000,
        stock_status: "in_stock",
        horizonte: "H1",
        bu: "Patient Engagement",
        squad: "Remote Care",
        owner: "Gustavo Lima",
        mercado: "B2B2C",
        revenue: "410k",
        pricing: "Por consulta realizada",
        problem: "Dificuldade de acesso a especialistas em regiões remotas e custos fixos altos de clínicas fisicas.",
        use_cases: "Pronto atendimento digital, Acompanhamento de pré-natal remoto, Tele-psicologia funcional",
        solutions: "Videochamada de baixa latência, Assinatura digital padrão ICP-Brasil, Dashboard para gestão de escalas",
        tech: "WebRTC, Node.js, React, PostgreSQL"
    }
];

const productsWithTags = products.map(p => ({ ...p, tag: p.horizonte }));

const ws = xlsx.utils.json_to_sheet(productsWithTags);
const wb = xlsx.utils.book_new();
xlsx.utils.book_append_sheet(wb, ws, 'Products');

const excelPath = path.resolve('./data/catalog.xlsx');
xlsx.writeFile(wb, excelPath);
console.log(`Successfully generated ${products.length} high-quality products in ${excelPath}`);
